### ISSUE TITLE
Packages Architecture / Organization

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-library#52]
How are there different types of packages that warrant working within separate areas of a repository, rather than a long list of heterogenous items within one directory?

**Comment by kevinmpowell** [comment]
Kevin's brain dump of the packages that need sorted:
![image](https://user-images.githubusercontent.com/979463/72758664-0baacf00-3b99-11ea-8469-1dfa92d311fb.png)

**Comment by nathanacurtis** [comment]
Diagram saved as separated Sketch file. `ESDS Package Architecture.sketch`

![image](https://user-images.githubusercontent.com/1165904/73672678-54738500-467b-11ea-8e08-71408a1703a4.png)

@kevinmpowell Closing this issue.
