### ISSUE TITLE
List Group [Propose]

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-library#58]
## Current Feature(s)

https://github.com/EightShapes/esds-library/blob/master/library/components/list/list.njk
(supports eyebrow, title, href, pill, and "description")

https://github.com/EightShapes/eightshapes-com/blob/master/components/link_list/link_list.njk
(used for Melzer posters, out of scope since list group wouldn't support images)
(used for systems fat footer of system posts)

https://github.com/EightShapes/esds-doc/blob/master/components/page_navigation/page_navigation.njk
(would the API / markup contract be used for sticky local navigation? This is desirable for eightshapes_com's articles, autogenerating a TOC for long posts)

## Proposed Features

MUST HAVE

- **Item names**, vertically stacked
- **Linked**: Linked or unlinked
- **Size**: Large or medium or small
- **Microcopy** line, above OR below (but not necessarily either)
- **Pill** (trails title as span element)
- **Icon** (on left)

TBD

- **Subsection** (indented, small text with medium top level, medium text with large top level)
- **Selected** item / active section
- **Microcopy location**, above or below?
- Eyebrow **heading** included or separate component? If so, include ARIA connection between header and list below it.

## Dependencies

`link`?
`heading`
`icon`

**Comment by nathanacurtis** [comment]
# Audit

## In Scope

![image](https://user-images.githubusercontent.com/1165904/73692645-b98ea100-46a2-11ea-9bc0-5dc326996dc2.png)

![image](https://user-images.githubusercontent.com/1165904/73692665-c3180900-46a2-11ea-9ac4-986e3b37cd1c.png)

![image](https://user-images.githubusercontent.com/1165904/73692704-d6c36f80-46a2-11ea-8d88-eda7ebe0f678.png)

![image](https://user-images.githubusercontent.com/1165904/73692820-1427fd00-46a3-11ea-92f6-7ad2c604f504.png)

![image](https://user-images.githubusercontent.com/1165904/73692834-1b4f0b00-46a3-11ea-997c-5359e095ed1c.png)

![image](https://user-images.githubusercontent.com/1165904/73692850-24d87300-46a3-11ea-8260-dbe7a2b167cc.png)

![image](https://user-images.githubusercontent.com/1165904/73692925-4c2f4000-46a3-11ea-8ed7-38ca865b16ac.png)

## Non-Instance/Exclude: 

Timeline as Media Object?

![image](https://user-images.githubusercontent.com/1165904/73692736-e8a51280-46a2-11ea-91da-2ca7bec3a006.png)

Long form text bullets

![image](https://user-images.githubusercontent.com/1165904/73692767-fd81a600-46a2-11ea-9dd5-dfd6c9a3938c.png)

![image](https://user-images.githubusercontent.com/1165904/73692878-31f56200-46a3-11ea-98bf-ee11e6b9bd66.png)

![image](https://user-images.githubusercontent.com/1165904/73692889-391c7000-46a3-11ea-9d11-28c39a3c0833.png)

**Comment by nathanacurtis** [comment]
@kevinmpowell @jamesmelzer Ready for review and comments here.

**Comment by kevinmpowell** [comment]
## Thoughts on how features could translate to an API
I'm not sure if this is the type of discussion you're wanting to have yet. If not, we can table this for later.

I'd consider building this as _two_ components: `<esds-list(group?)>` & `<esds-list-item>`

That changes the API usage from:
```html
<esds-list size="large" items="[{"label":"text", "icon":"pill", etc. etc..."></esds-list>
```
To:
```html
<esds-list size="large">
  <esds-list-item label="text" icon="pill"></esds-list>
  <esds-list-item label="text" icon="pill"></esds-list>
</esds-list>
```

The latter is far easier to write validation rules for since `list-item` can have top-level props and not values buried in a complex JSON structure.

As I think about your must haves and where they'd land as props:
> Item names, vertically stacked

list-item prop
> Linked: Linked or unlinked

list-item prop
> Size: Large or medium or small

list prop - assuming list item sizes should not be mixed
> Microcopy line, above OR below (but not necessarily either)

list-item prop
> Pill (trails title as span element)

separate Pill component, passed into a named slot on list-item
> Icon (on left)

separate Icon component, passed into a named slot on list-item

>TBD
> Subsection (indented, small text with medium top level, medium text with large top level)

Maybe another wrapper component, or, mirroring native `<ul>` behavior, a nested `esds-list`?
```html
<esds-list>
  <esds-list-item>Item 1</esds-list-item>
  <esds-list>
    <esds-list-item>Subsection Item 1</esds-list-item>
    <esds-list-item>Subsection Item 2</esds-list-item>
  </esds-list>
</esds-list>
```
> Selected item / active section

list-item prop

> Microcopy location, above or below?

list-item prop, maybe a named slot

> Eyebrow heading included or separate component? If so, include ARIA connection between header and list below it.

Likely a peer component to list-item nested inside list:
```html
<esds-list>
  <esds-heading variant="eyebrow">List Heading</esds-heading>
  <esds-list-item>Item 1</esds-list-item>
  <esds-list-item>Item 2</esds-list-item>
</esds-list>
```

## Additional Features I've seen elsewhere
* Badging, some sort of "count" per list item - often used in facets for table data
* Checkboxes - again, facets for table data

**Comment by jamesmelzer** [comment]
> Pill (trails title as span element)

I second Kevin's recommendation to put simple pill in its own component and leave a named slot for it in list item. That also opens the door for other uses for that slot (star ratings? time stamps?)

> TBD: Subsection (indented, small text with medium top level, medium text with large top level)

I don't see an example of this today. I agree with the visual expectation that it's one size step down from default. 

> I'd consider building this as two components: `<esds-list(group?)>` & `<esds-list-item>`

I would expect `<esds-list-group>` to have little to no actual styling, given that `selected` / `active` items would be set and styled at the `<esds-list-item>` level. Perhaps just a trailing space below? 

Design Tool implications: 

- Hey, we can legitimated to ALL of this in Sketch and Figma now! 
- Flexible list item with optional icon and tag slots inline
- List item variations for microcopy (above/below?)
- Container list-group to hold the group and provide trailing spacer.

**Comment by nathanacurtis** [comment]
@kevinmpowell Unlike some groups, I'm very willing to have an API discussion.

- I like your model, although I prefer `esds-list-group` over `esds-list` for specificity. `-list` alone could be confused with or used for other things.
- I'm not as confident a group heading is actually in a list itself, nesting the list within it. That's not the model I'd expect. A heading may appear when there's only one list below it.
- Let's build what we need. We won't need `checkbox`.

@jamesmelzer and I had a good discussion about `list-group` as a Figma object, starting the process of discussing how its constructed there.
