### ISSUE TITLE
Card [Propose]

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-library#59]
## Current Features

https://github.com/EightShapes/esds-library/blob/master/library/components/card/card.njk

- Links entire card block
- Uses "CTA" paragraph slot to put what appears to be a link (even though the whole card is linked)
- Embeds thumbnail as subcomponent using DiscEd's Comet markup approach
- Supports content container backgrounds: white, light, dark, black, brand, and dark photograph

## Proposed Features

MUST HAVE

- additional card block class
- title (applies `heading`)
- description
- href / destination
- thumbnail (applies `thumbnail`)
    - block (true/false; could fill with icon w/o URL)
    - URL
- microcopy/metadata/type
- content slot
- actions slot
- focus ring for toggling across cards
- hover alter content container background color
- hover enlarge thumbnail, triggered if hovering card (not just thumbnail?)

SHOULD HAVE

- isolated tests
    - design system articles, thumbnails
    - case studies, thumbnails
    - without thumbnail image, only thumbnail ...color or icon?
- composition tests
    - with `button` in actions slot
    - with `icon`s/`button--icon`s in actions slot
    - with random crap in content slot

TBD

- merge `tile` with this?
- max width
- Content container background color (dark, black, white, light)
- thumbnail aspect ratio (default, square?)
- link block (title only? title and image? entire card block?)

## Dependencies

`thumbnail`
`heading`
`icon`?
`link`?

**Comment by nathanacurtis** [comment]
## Current Use of esds-card

![image](https://user-images.githubusercontent.com/1165904/73847091-9aebef80-47f3-11ea-9b20-01caa7bf779c.png)

![image](https://user-images.githubusercontent.com/1165904/73847113-a2ab9400-47f3-11ea-9cc6-a45caf41500f.png)

![image](https://user-images.githubusercontent.com/1165904/73847132-a808de80-47f3-11ea-84c4-c90464ebc653.png)

## Current Use of esds-tile

![image](https://user-images.githubusercontent.com/1165904/73847164-bb1bae80-47f3-11ea-9f83-f873287b6f18.png)

![image](https://user-images.githubusercontent.com/1165904/73847173-c1aa2600-47f3-11ea-85f8-3e26666282e5.png)

![image](https://user-images.githubusercontent.com/1165904/73847188-c5d64380-47f3-11ea-9df3-2cb9b7ba8768.png)

Uses ` esds-tiles--translucent-white`
![image](https://user-images.githubusercontent.com/1165904/73847240-dc7c9a80-47f3-11ea-9aa9-ba7b5bc253f5.png)

**Comment by nathanacurtis** [comment]
@kevinmpowell @jamesmelzer Ready for review and comments here.

**Comment by kevinmpowell** [comment]
> MUST HAVE
additional card block class

What's the additional card block class needed for? Is there a common use case?

> title (applies heading)

Is title required? I could see an Image + Description only variant if the title is part of the image.

> description
href / destination
thumbnail (applies thumbnail)

thumbnail could be a named slot. Especially if we have a separate `esds-thumbnail` component we're composing into card. It depends on how much of `esds-thumbnail`'s API we want to expose.
> * block (true/false; could fill with icon w/o URL)

The name "block" is unclear to me. Does it just represent the presence/absence of URL? If so, it's unneeded since it could be auto-detected

> * URL

Recommend sticking with the term "href" here. `thumbnailHref` if needed.

---
I don't have any specific comments on the rest.
We should also consider the layout of these. Is there an `<esds-card-grid>` that is used as a wrapper? Or a more generic `<esds-grid>` that we leverage?

**Comment by jamesmelzer** [comment]
### Proposal

- Needs basics of responsive behavior - are we sticking with today's "relatively squishy" cards, that are largely governed by their containing card-grid? 

### Design tooling implications

- I believe we would need separate variations for card and tile (image-less card) to account for the rounded corners. That's not something we can vary based on content. We can still call them all card (e.g. `card` vs `card--no-image` ?)
- Both tools are not great at componentizing Long Form Text. Examples like the tile with heading and bullets will require some additional support to create, but shouldn't be a heavy lift.

**Comment by jamesmelzer** [comment]
* Can we make a decision on merging with tile? Most of my questions revolve around that. If we merge with tile, that adds requirements (linked heading, list, and microcopy last). 
* Do we have existing design for icon treatment as an image fallback? I don't see one in the examples. I vaguely remember Discovery's design, but will need to see (or design) an EightShapes-specific treatment. 
* Do you want states explicitly modeled in Figma symbols (for designers), or just as a sticker sheet illustration (for the developer making the component)?

**Comment by nathanacurtis** [comment]
@jamesmelzer 

* IMHO, `Card` and `Tile` are different components. They have different design intent. While their elements are the same, the _kinds_ of content that go in those elements is different, one to reflect an _object_ and the other to reflect a _marketing message_. I'd be most 😍 if they shared some styling mechanics via tokens and mixins.
* For `Card` without image, that's a nice-to-have for Smashing but out of scope for our site.
* Woosh, your question framed the options in a completely opposite way I would. I've always thought "sticker sheets" are for designers that reuse symbols, and states modeled are (imho) always for the developers to build the component correctly. You use these terms in reverse. At Smashing, we are concentrating on the system designer-to-system developer workflow more.

**Comment by nathanacurtis** [comment]
@kevinmpowell 

- The additional card block class would be my assumed way of hooking in a block-level class to override styles for nested elements based on my context. I could imagine almost every component enabling this.
- In my belief of `Card`, Title is always required, since a cards refers to an object.
- I see `Thumbnail` more as a nested separate component that nevertheless isn't put in via slot but, like in our conversation about MDS List Group, exposes it's (really simple) API through the `Card`.
- For `Thumbnail` block, that's more just the scope of "Can you have a `Card` without a thumbnail?" I think you can.
- For `URL` v `href`, agree. Consider the scoping in [Propose] as directionally / suggestively meaningful but not a firm API recommendation.
