### ISSUE TITLE
Icon [Propose]

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-library#64]
What's the required and optional potential features of the icon component?

- Size: S? M? L? (probably needs a canvasing through `eightshapes_com` and tokens to confirm)
- Additional class?
- Name (linking it with an SVG?)
- Title (for assistive devices?)

**Comment by kevinmpowell** [comment]
# Icon API Proposal

## Slots
| name | default | values | description |
|---|---|---|---|
| size | 'medium' | 'small', 'medium', 'large' | Sets height and width of the icon |
| title | none | Any string | Adds a visibly hidden `<title>` element with a corresponding `aria-labelledby` tag when provided. Used only when icons stand alone without other context. |
| use | EsdsIconAngleRight | string or ES6 module | Determines which icon will be shown. When leveraging the Icon sprite, the id of the sprite symbol should be provided (ex: `#angle-right`). When using ES6 modules, pass the name of the module (ex: `EsdsIconAngleRight`). See usage examples below. |

## Usage Examples
### Icon Sprite Usage
```html
<script src="path/to/@eightshapes/esds-icon"/>
<div style="display: none;">
  <!-- import esds-icons.svg sprite sheet -->
</div>

<a href="#">Follow us on twitter <esds-icon use="#twitter"></esds-icon></a> 
<esds-icon use="#stopwatch" size="large" title="Workshop Schedule"></esds-icon>
```

### ES6 module usage, requires JS framework or something like `lit-html`
```html
<script type="module">
  import { EsdsIconTwitter } from '/path/to/@eightshapes/esds-icons';
  import '/path/to/@eightshapes/esds-icon';
  import { html, render } from '/path/to/lit-html';
  
  const iconExample = html`
    <esds-icon use="${EsdsIconTwitter}"></esds-icon>
  `;

  render(iconExample, document.getElementById("target");
  
</script>

<div id="target"></div>
```

### Internal component usage (composite component)
```js
import { EsdsIconClose } from '/path/to/@eightshapes/esds-icons';
import { EsdsIcon } from '/path/to/@eightshapes/esds-icon';

class EsdsModal extends LitElement {
  ...
  render() {
    return html`
      <div class="esds-modal">
        <button class="esds-modal__close" hiddenLabel>
          Close
          <esds-icon slot="icon-left" use="${EsdsIconClose}"></esds-icon>            
      </div>
    `;
  }
}
```

## Additional API Notes
* By default the icon will have `role="presentation"` to hide the SVG content from screenreaders
  * When a `title` is provided, `role="presentation"` will be removed
* No slots, methods, or events for Icon

## Current Icon Usage
I'm not sure what sizes should map to our small, medium, & large. 16x16 seems to be the most common use case currently.

![image](https://user-images.githubusercontent.com/979463/74675914-5446af80-517a-11ea-8163-a103d6e52ca4.png)

![image](https://user-images.githubusercontent.com/979463/74675991-8e17b600-517a-11ea-8481-3ee1603fdc8e.png)

![image](https://user-images.githubusercontent.com/979463/74676060-b9020a00-517a-11ea-81af-ff9605309c15.png)

![image](https://user-images.githubusercontent.com/979463/74676170-08483a80-517b-11ea-8caf-48cd054ed13c.png)

**Comment by nathanacurtis** [comment]
Feedback:
- I was looking more for `name` rather than `use` for the name of the icon. I'm low-to-medium Cap on that.
- Is a prop useful and relevant for vertical alignment when inline, such as bottom, middle and top?
- Is there a reason you have to include the # in the `use` prop? I'd have expected to use just the label without the #.
- Should we use the terminology of **nested** use instead of internal/composite?
- Isn't the default of `presentation` more risky, in that implementers will often exclude switching it? Wouldn't it be safer to default it to on and then have someone hide it from screenreaders?

**Comment by kevinmpowell** [comment]
> * I was looking more for `name` rather than `use` for the name of the icon. I'm low-to-medium Cap on that.

`use` mirrors the underlying SVG attribute name, and in the case where the JS Module is being passed in, it's not really a name, it's a javascript object. So "use" works in both cases. Either "Use" this JS Module, or "use" this sprite reference.

> * Is a prop useful and relevant for vertical alignment when inline, such as bottom, middle and top?

Vertical alignment is typically handled by the parent context. A table cell, or flex-box child will have the alignment property and the icon will inherit that alignment context.

> * Is there a reason you have to include the # in the `use` prop? I'd have expected to use just the label without the #.

It's the differentiator between using the sprite sheet method vs the JS Module method. The component will use it internally as well to switch between those rendering modes.

> * Should we use the terminology of **nested** use instead of internal/composite?

Sure. Low cap on that for me.

> * Isn't the default of `presentation` more risky, in that implementers will often exclude switching it? Wouldn't it be safer to default it to on and then have someone hide it from screenreaders?

A standalone icon is used in less than 10% of use cases in my experience. In the other 90% we'd have to manually add the `role="presentation"` attribute. Setting it by default makes the component easier to use. I think the risk is low. If you're implementing a standalone icon you're doing something very intentional.

**Comment by nathanacurtis** [comment]
@kevinmpowell Thanks for the responses. Approved.
