### ISSUE TITLE
List Group [Design]

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-library#65]
[PROPOSE] https://github.com/EightShapes/esds-library/issues/58
Figma https://www.figma.com/file/uKe4KNJ0B4hzLSpwOzIC7y/esds-library?node-id=25%3A3

**Comment by nathanacurtis** [comment]
@jamesmelzer Any quick idea how to make items within a group fill the frame?

![image](https://user-images.githubusercontent.com/1165904/74846024-d6131600-52fd-11ea-8a58-42b7df502ca9.png)

**Comment by nathanacurtis** [comment]
@jamesmelzer I've already run into composition that I'll want to get right relative to components for:
- `caret-right` as an available icon at a size
- `icon` at a size consuming a specific icon like `caret-right`
- `list-group-item--icon-label pair` consuming `icon` in which I can swap `caret-right` and `caret-down`

Let's spend some time setting up the hierarchy in Figma.

![image](https://user-images.githubusercontent.com/1165904/74846223-225e5600-52fe-11ea-83e6-3d34cd8bccc5.png)

**Comment by nathanacurtis** [comment]
@kevinmpowell @jamesmelzer 

I've done a round of `esds-list-group` design, posted in Figma. 
![image](https://user-images.githubusercontent.com/1165904/74984739-502dc280-5404-11ea-9dd3-6e22c2afde5d.png)

@jamesmelzer I'm not exactly sure how to invite @kevinmpowell to review/comment. Let's do that tomorrow during Share & Care?

**Comment by jamesmelzer** [comment]
@nathanacurtis I invited Kevin (and Chris!) to Figma so they can collaborate with us as needed. Once they accept those invites, they should be valid targets for comments to invite feedback, etc.

**Comment by nathanacurtis** [comment]
@jamesmelzer But not @brownorama ? Wow. What does that mean?

**Comment by jamesmelzer** [comment]
@nathanacurtis It means he's already in there.
