### ISSUE TITLE
Card [Code]

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-library#68]
**Update August 2020:** Revise based on new designs in [Figma](https://www.figma.com/file/uKe4KNJ0B4hzLSpwOzIC7y/esds-library?node-id=1127%3A203)

Propose: https://github.com/EightShapes/esds-library/issues/59

* [x] Add build tooling to `esds-visual-style` so file watchers work correctly all the way up the stack. I want to be able to save a token and see that automatically refresh Card's storybook examples with the new value.
* [x] Default Card should have an image (background color + icon)
* [x] Separate Thumbnail component
* [x] States - don't embed states in artwork - where do you put labels? - Need label styles
* [x] Add a slot placeholder that shows borders - doc bits
* [x] "Content" prop should be "Description" and be above content <slot>
* [x] Background Color Demo
* [x] Add name spacing functionality
* [x] Fix Docs view...currently inheriting hostile styles
* [x] Knobs example
* [x] IE 11 Compatibility
* [x] Design Updates (including text-crop)
* [x] Incorporate Inclusive Component Best Practices for Card (link, aria, etc.)
* [x] Props tables in storybook

**Comment by jamesmelzer** [comment]
@kevin I suggested some opinionated “slots” for card, shown at the end of this Card [Design] ticket (actions, content, thumbnail). Feedback appreciated as you dive into code on it. 
https://github.com/EightShapes/esds-library/issues/67

**Comment by nathanacurtis** [comment]
@jamesmelzer I don't believe `thumbnail` is a slot. It'd be a subcomponent through which the API of `card` would enable to to interact with the API of `thumbnail` within `card`. I believe this is in contrast to `actions` and `content`, both of which are unopinionated, true slots that – for the Figma file – have well-defined regions / space you can drop stuff into OR omit. I'd also assume the Figma file would have examples created exhibiting content/elements within those slots.

**Comment by kevinmpowell** [comment]
* Default Card should have an image (background color + icon)
* Separate Thumbnail component
* States - don't embed states in artwork - where do you put labels? - Need label styles
* Add a slot placeholder that shows borders - doc bits

**Comment by jamesmelzer** [comment]
I added the content slot below the description along with two examples. 

BTW, Kevin the spacing is a little fussy. 

* 24 px inset for the entire content block
* eyebrow, title, description, and content slot each stacked with 8px between
* actions stacked with 16px between it and any of the elements that could appear before it (which suggests an implementation with 8px margin above it. Open to alternatives...)

![Screen Shot 2020-03-09 at 10 18 05 AM](https://user-images.githubusercontent.com/1207666/76221370-5c30c700-61ef-11ea-9235-46dd6f92b818.png)

**Comment by nathanacurtis** [comment]
@jamesmelzer I think this spacing model makes sense.

When documenting slots and spacing models, consider (a) using dashed lines for all slots (here, actions wasn't dashed) and including a tan/beige (eyedrop from Chrome) spacer annotation at the base of each slot and other element.

Consider separating title and description by 16, not 8 (my Cap score? 6ish).

**Comment by jamesmelzer** [comment]
@kevinmpowell Increased spacing between title and description from 8px (S) to 16px (M). 

@nathanacurtis Added example annotations and components for annotations, so we can iterate those easily. 

![Screen Shot 2020-03-12 at 12 02 43 PM](https://user-images.githubusercontent.com/1207666/76541626-44a94680-645a-11ea-9887-201145761c66.png) ![Screen Shot 2020-03-12 at 12 02 52 PM](https://user-images.githubusercontent.com/1207666/76541642-470ba080-645a-11ea-9923-24aae0b809aa.png)

![Screen Shot 2020-03-12 at 12 08 30 PM](https://user-images.githubusercontent.com/1207666/76541659-4bd05480-645a-11ea-9bd2-6ba0df4810f7.png)

**Comment by kevinmpowell** [comment]
@jamesmelzer did you also increase the spacing between description and content and content and action slots? The visual _reads_ "16" but it still looks like "8" to my eye compared to the space between Title and description.

**Comment by jamesmelzer** [comment]
@kevinmpowell all 16s

**Comment by kevinmpowell** [comment]
Thanks for clarifying. The additional vertical space caused by the descender of the title made it seem larger.

**Comment by jamesmelzer** [comment]
Barlow Semi Condensed sits very low in its text block. I'll be interested to see how it works in code.
