### ISSUE TITLE
Tabs [Propose]

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-library#78]
### Must Have

- Includes `Medium` and `Small` variants
- Swipeable in conditions of insufficient width

### Not Required

- Responsiveness

**Comment by nathanacurtis** [comment]
@jamesmelzer @kevinmpowell Very light Tabs [Propose] ready for comment. Let me know what you need to know.

**Comment by jamesmelzer** [comment]
@nathanacurtis 

* This component has different use cases in different libraries; .com and doc need different things. Does `small` explicitly include the tabs used in (library) code viewer, or is that a component-specific extension? I could see `tabs` providing basic styling including spacing, but code viewer overriding the active state color. 
* Color/context requirements? Does it follow the usual 4 background options? (Should we assume that for every library component?)

**Comment by nathanacurtis** [comment]
@jamesmelzer IMHO, I don't know that `esds-tabs` will be a direct dependency of `esds-code-example-viewer`. Instead, at most, I suspect we'd use lower level visual tooling (tokens, etc) to bring consistency. // cc @kevinmpowell 

For background colors, yes, I think I'd like to design for four backgrounds across all atomic things, including @bfaulkner-1 's work. I'll setup `esds-list-group` to emulate a Figma artboard structure.

**Comment by kevinmpowell** [comment]
> Instead, at most, I suspect we'd use lower level visual tooling (tokens, etc) to bring consistency. // cc @kevinmpowell

Agreed. 

If it helps the design, the implementation will likely be two separate components. A parent and children:

```
<esds-tabs>
  <esds-tab label="Tab One">
    <!-- Tab One Content-->
  </esds-tab>
  <esds-tab label="Tab Two">
    <!-- Tab Two Content-->
  </esds-tab>
</esds-tabs>
```

Not vital to know for the design, but perhaps helpful.

✅  **Approved with comments**
