### ISSUE TITLE
Long Form Typography [Design]

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-library#79]

**Comment by nathanacurtis** [comment]
@kevinmpowell @jamesmelzer For now, I'm thinking we just need spacing between pairs of common elements in article wells. I've started this documentation as the `Long Form Text` component in Figma's Light Mode board (noting, however, that this is really _Technical_ Long Form Text distinct from _Blog_ Long Form Text). Is this enough to start?

![image](https://user-images.githubusercontent.com/1165904/95256376-ba0ea700-07f0-11eb-9ecc-73efa262b732.png)

**Comment by jamesmelzer** [comment]
This is a useful foundation. Additional combinations, which may only need a single representation here:
- Paragraph below a block. You only show headings. 
- Lists. If they have spacing distinct from paragraph, such as extra trailing space, how do they interact with headings, paragraphs, and blocks?

**Comment by jamesmelzer** [comment]
Also you’re missing a spacing indicator under “default” heading. Spacing looks correct though.

**Comment by kevinmpowell** [comment]
Image captions? Quotes? (Rare)
I also second what James mentioned. 
It's looking good.

**Comment by nathanacurtis** [comment]
@kevinmpowell @jamesmelzer 

In applying `do-dont`, `code-example` and `image-with-caption`, I've resolved that a good pattern for such objects to be applying a top-margin of `32px` and an _extra_ bottom-margin of `16px`, if we can get those to not collapse with the top-margin that follows.

![image](https://user-images.githubusercontent.com/1165904/95334461-21256d80-087c-11eb-9120-0e1899444d83.png)
