### ISSUE TITLE
Icons [Design Asset]

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-library#83]
### Icons to Convert

![image](https://user-images.githubusercontent.com/1165904/75160251-b017b800-56e7-11ea-9ff8-e49fcb6120ce.png)

**Comment by jamesmelzer** [comment]
Figma
https://www.figma.com/file/uKe4KNJ0B4hzLSpwOzIC7y/esds-library?node-id=90%3A0

Ready for visual review.
