### ISSUE TITLE
Button [Design Asset]

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-library#84]
### Design Starting Point

![image](https://user-images.githubusercontent.com/1165904/75160372-ddfcfc80-56e7-11ea-940f-ba88a12ea4bd.png)

### Must Have

- 'Large', 'Medium', `Small'
- With icon, Only icon
- Types: Primary, secondary, flat, brand (white on orange or orange on white), and ghost
- Settings: Light & dark (varies teal, too)
- States: default, hover, focus, active

**Comment by nathanacurtis** [comment]
Example: EightShapes.com

![image](https://user-images.githubusercontent.com/1165904/75160460-04bb3300-56e8-11ea-92f2-b3e1db8e580c.png)

This would be a `Large` `Brand` button

**Comment by jamesmelzer** [comment]
Learn More could/should be a `flat` button

![Screen Shot 2020-02-24 at 10 24 32 AM](https://user-images.githubusercontent.com/1207666/75165205-0852b800-56f0-11ea-8f1b-63457ca0f127.png)

**Comment by jamesmelzer** [comment]
Figma
https://www.figma.com/file/uKe4KNJ0B4hzLSpwOzIC7y/esds-library?node-id=150%3A1112

Ready for visual review.

**Comment by jamesmelzer** [comment]
@bfaulkner-1  FYI, before we get into a discussion of component hierarchy, I made one consistency change to button... 

![Screen Shot 2020-03-03 at 9 26 42 AM](https://user-images.githubusercontent.com/1207666/75785074-2db77580-5d31-11ea-8ea7-232161060eb8.png)
